import React, {Component} from 'react';

export class Security extends Component {
  constructor(props) {
    super(props);
    this.state = {
      showQR: false,
    };
  }

  componentDidMount = () => {};

  render() {
    const Profile = this.props.heading;
    return (
      <>
        <div className="containment">
          <div className="balances">
            <h3>Change Login Password</h3>
            <hr />
            <div className="centered">
              <div className="balances-form mt-2">
                <div className="a5-form-field">
                  <label>Current Password</label>
                  <input type="password" />
                </div>
                <div className="a5-form-field">
                  <label>New Password</label>
                  <input type="password" />
                </div>
                <div className="a5-form-field">
                  <label>Confirm Password</label>
                  <input type="password" />
                </div>
                <div className="a5-form-field">
                  <div className="a5-form-btn-grp">
                    <button className="form-btn-yellow">Update Password</button>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="balances pt-5 mt-2">
            <div className="balance-notice">
              <h3>Two Factor Authentication</h3>
              <p>
                Two Factor Authentication adds extra security to your account.
                Once activated it will require you to enter a unique
                verification code generated by the app on your device or sent
                via SMS text message, in addition to your username and password.
              </p>
            </div>
            <div className="balance-ga-notice mt-5 mb-5 d-flex">
              <img src="db-assets/google-authenticator-2 1.svg" alt="" />
              <p>
                <span style={{color: ' var(--yellow-text)'}}>
                  Google Authenticator
                </span>
                to verify your account every time you sign in
              </p>
              <button
                onClick={() => this.setState(() => ({showQR: true}))}
                className="a5-button-primary"
              >
                ENABLE
              </button>
            </div>
            {this.state.showQR ? (
              <>
                <div className="centered d-flex justify-content-center">
                  <div className="qr-container d-flex">
                    <img src="db-assets/qr_code.svg" />
                    <div className="two-factor-code">
                      <input
                        value="237gj h64d1 5907 c694 02"
                        type="text"
                        readOnly
                      />
                      <img src="db-assets/copy-icon.svg" alt="" />
                      <p>
                        If you are unable to scan this QR Code, please insert
                        this key into the app manually.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="centered">
                  <div className="balances-form mt-2">
                    <div className="a5-form-field">
                      <label>Enter Code</label>
                      <input type="text" />
                    </div>
                    <div className="a5-form-field">
                      <div className="a5-form-btn-grp">
                        <button className="form-btn-yellow">Update MFA</button>
                      </div>
                    </div>
                  </div>
                </div>
              </>
            ) : (
              <></>
            )}
          </div>
        </div>
      </>
    );
  }
}

export default Security;
